### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by quietone1** [wodby/docker4drupal#210]
First time trying to use this. Taking the basic route and following the instructions at https://docker4drupal.readthedocs.io/en/latest/#1-run-vanilla-drupal-from-image-default. No changes made to docker-compose.yml and docker-compose up -d fails. 

Here is where the errors started.

```
Creating d8dev1_mariadb_1

ERROR: for d8dev1_mailhog_1  dictionary update sequence element #0 has length 23; 2 is required

Recreating d8dev1_php_1 ... error

Creating d8dev1_mariadb_1 ... done

ERROR: for php  no such image: sha256:177e2c6bd6831252b64dd622c945de3f7a35be11933cac4d346d50ab9a413b75: No such image: sha256:177e2c6bd6831252b64dd622c945de3f7a35be11933cac4d346d50ab9a413b75

ERROR: for mailhog  dictionary update sequence element #0 has length 23; 2 is required

ERROR: for portainer  dictionary update sequence element #0 has length 25; 2 is required
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 952, in up
  File "compose/project.py", line 455, in up
  File "compose/parallel.py", line 70, in parallel_execute
ValueError: dictionary update sequence element #0 has length 25; 2 is required
Failed to execute script docker-compose   
```
These images were downloaded:
```
$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
traefik               latest              79f625300972        2 days ago          45.6MB
portainer/portainer   latest              6cafdc66421d        3 days ago          33.1MB
wodby/drupal-nginx    8-1.13-3.0.1        aafde4bcfbe2        5 weeks ago         31.2MB
wodby/drupal          8-7.1-3.0.0         1e6618bc71c9        5 weeks ago         362MB
wodby/mariadb         10.1-2.3.5          37582351402a        2 months ago        205MB
mailhog/mailhog       latest              669347153085        7 months ago        19.1MB
```
### Codebase
Built-in vanilla Drupal
  
### Host OS 
Debian Stretch

### Docker info output
```$ docker info
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 7
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: ithilien
ID: ZXR4:MQLX:4HLZ:YQNH:EJJE:5S4Q:RXA2:V4OO:T7VF:MGMQ:2ISN:246V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

### Docker compose file
Downloaded docker-compose.yml v2.40. Made no changes to the file.

### Logs output
```Attaching to 049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [NEW RELIC] Skipping...
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [Thu Nov 16 02:04:02.767089 2017] [mpm_prefork:notice] [pid 22] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [Thu Nov 16 02:04:02.767115 2017] [mpm_prefork:info] [pid 22] AH00164: Server built: Sep 20 2017 04:37:43
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [Thu Nov 16 02:04:02.767121 2017] [core:notice] [pid 22] AH00094: Command line: 'apache2 -D FOREGROUND'
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [NEW RELIC] Skipping...
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [Thu Nov 16 22:35:19.352604 2017] [mpm_prefork:notice] [pid 21] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [Thu Nov 16 22:35:19.352622 2017] [mpm_prefork:info] [pid 21] AH00164: Server built: Sep 20 2017 04:37:43
049aaef39184_049aaef39184_049aaef39184_d8dev1_php_1 | [Thu Nov 16 22:35:19.352627 2017] [core:notice] [pid 21] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by PavelPrischepa** [comment]
Downgrading docker-compose to 1.16 should solve the issue.

**Comment by finex** [comment]
Did you try to upgrade to 1.17.1?

**Comment by quietone1** [comment]
Thank you. Both versions got me past the python dictionary error.
