### ISSUE TITLE
Arch linux - ascii codec can't decode byte 0xe2...

### ISSUE THREAD

**Issue by ColinRyan** [wodby/docker4drupal#219]
### Codebase
build-in
  
### Host OS 
Arch

### Docker info output
```
Containers: 2                                                                                                                                                                                 
 Running: 0
 Paused: 0
 Stopped: 2
Images: 230
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.8-2-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.663GiB
Name: arch
ID: 4DRX:LG2Y:A4TI:R3AK:3JXP:PQ2Y:XXKQ:ZJ5O:YQCK:75UF:GLD5:A33O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

### Docker compose file
```yml
Exactly what's in the repo, no changes.
```

When I run
```
docker-compose up -d
```
I get 
```
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/bin/docker-compose", line 11, in <module>                                                                                                                                         
    sys.exit(main())                                                                                                                                                                           
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 68, in main                                                                                                                
    command()                                                                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 118, in perform_command                                                                                                    
    project = project_from_options('.', options)                                                                                                                                               
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 37, in project_from_options                                                                                             
    override_dir=options.get('--project-directory'),                                                                                                                                           
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 87, in get_project                                                                                                      
    config_details = config.find(project_dir, config_path, environment, override_dir)                                                                                                          
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 274, in find                                                                                                          
    [ConfigFile.from_filename(f) for f in filenames],                                                                                                                                          
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 274, in <listcomp>                                                                                                    
    [ConfigFile.from_filename(f) for f in filenames],                                                                                                                                          
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 174, in from_filename                                                                                                 
    return cls(filename, load_yaml(filename))                                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 1303, in load_yaml                                                                                                    
    return yaml.safe_load(fh)                                                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load                                                                                                              
    return load(stream, SafeLoader)                                                                                                                                                            
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 70, in load                                                                                                                   
    loader = Loader(stream)                                                                                                                                                                    
  File "/usr/lib/python3.6/site-packages/yaml/loader.py", line 24, in __init__                                                                                                                 
    Reader.__init__(self, stream)                                                                                                                                                              
  File "/usr/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__                                                                                                                 
    self.determine_encoding()                                                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding                                                                                                      
    self.update_raw()                                                                                                                                                                          
  File "/usr/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw                                                                                                              
    data = self.stream.read(size)                                                                                                                                                              
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode                                                                                                                             
    return codecs.ascii_decode(input, self.errors)[0]                                                                                                                                          
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 436: ordinal not in range(128)
```

Anyone have any ideas?

**Comment by csandanov** [comment]
It's a docker-compose issue, see https://github.com/docker/compose/issues
