### ISSUE TITLE
Issue with the latest Docker version 17.12.0-ce-win46(15048)

### ISSUE THREAD

**Issue by Max-Zviagintsev** [wodby/docker4drupal#229]
### Codebase
Mounted codebase
  
### Host OS 
Windows 10 pro

### Docker info output
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 22
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d017626
ID: CCTX:7OVM:WTQ7:QL5G:NYBO:B2LN:ZPIB:ZFLZ:LEG6:R5QF:LA7X:OOUP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 36
 System Time: 2018-01-11T11:56:06.4444136Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Docker compose file
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - ./mariadb/:/var/lib/mysql # I want to manage volumes manually.

  php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-3.0.0
#    image: wodby/drupal:8-7.0-3.0.0
#    image: wodby/drupal:7-7.1-3.0.0
#    image: wodby/drupal:7-7.0-3.0.0
#    image: wodby/drupal:7-5.6-3.0.0
#    image: wodby/drupal:6-5.6-3.0.0
#    image: wodby/drupal:6-5.3-3.0.0
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.1-3.0.0
#    image: wodby/drupal-php:7.0-3.0.0
#    image: wodby/drupal-php:5.6-3.0.0
#    image: wodby/drupal-php:5.3-3.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: "10.0.75.1"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
    volumes:
      - ./:/var/www/html
## Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-nginx:8-1.13-3.0.1
#    image: wodby/drupal-nginx:7-1.13-3.0.1
#    image: wodby/drupal-nginx:6-1.13-3.0.1
#    image: wodby/drupal-nginx:8-1.12-3.0.1
#    image: wodby/drupal-nginx:7-1.12-3.0.1
#    image: wodby/drupal-nginx:6-1.12-3.0.1
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
# Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

#  apache:
#    image: wodby/php-apache:2.4-2.0.0
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - codebase:/var/www/html
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

#  varnish:
#    image: wodby/drupal-varnish:4.1-2.2.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.drupal.docker.localhost'

  redis:
   Hi!
My dev site is not reacheble since the latest docker update. It acts weird when starting, showing php container 2 times and no mariaDB.

 D:\web-dev\liza-shop> docker-compose up -d
Starting lizashop_redis_1 ...
Starting lizashop_php_1 ...
Starting lizashop_mailhog_1 ...
Starting lizashop_traefik_1 ...
Starting lizashop_portainer_1 ...
Starting lizashop_php_1 ... done
Starting lizashop_nginx_1 ... done

However, MariaDB shows as running:

PS D:\web-dev\liza-shop> docker-compose stop
Stopping lizashop_nginx_1     ... done
Stopping lizashop_php_1       ... done
Stopping lizashop_mailhog_1   ... done
Stopping lizashop_traefik_1   ... done
Stopping lizashop_redis_1     ... done
Stopping lizashop_mariadb_1   ... done
Stopping lizashop_portainer_1 ... done

Anyway, when I'm trying to open my site, it says "File not found". Maybe this is the same issue: https://forums.docker.com/t/volumes-not-mounting-after-upgrade-to-version-17-12-0-ce-win46-15048/44220/2

image: wodby/redis:3.2-2.1.3
##    image: wodby/redis:4.0-2.1.3

#  adminer:
#    image: wodby/adminer:4.3-1.1.0
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:adminer.drupal.docker.localhost'

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - 'traefik.backend=pma'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:pma.drupal.docker.localhost'

#  solr:
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-solr:8-6.6-2.2.0
##    image: wodby/drupal-solr:7-5.4-2.2.0
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - 'traefik.frontend.rule=Host:solr.drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

#  nodejs:
#    image: wodby/drupal-node:1.0-1.0.0
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:nodejs.drupal.docker.localhost'
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  node:
#    image: node:alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.drupal.docker.localhost'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: wodby/memcached:1.4-2.0.0

#  rsyslog:
#    image: wodby/rsyslog

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:2.10.0
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false

#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY

#  webgrind:
#    image: wodby/webgrind:1.5-1.0.0
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.drupal.docker.localhost'
#    volumes:
#      - files:/mnt/files

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:

```

### Logs output
| time="2017-11-12T20:06:03Z" level=warning msg="Error forwarding to http://:80, err: context canceled"
php_1        | [13-Nov-2017 22:45:50] WARNING: [pool www] child 50 said into stderr: "#12 /var/www/html/web/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)"
mailhog_1    | [APIv1] KEEPALIVE /api/v1/events
mariadb_1    | 2017-11-08  0:58:23 140526715271912 [Note] InnoDB: Starting shutdown...
redis_1      | 1:M 12 Nov 18:18:17.040 # Redis is now ready to exit, bye bye...
nginx_1      | 172.18.0.5 - - [13/Nov/2017:21:39:07 +0000] "GET /core/assets/vendor/jquery-once/jquery.once.min.js.map HTTP/1.1" 200 834 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
traefik_1    | time="2017-11-12T20:06:03Z" level=warning msg="Error forwarding to http://:80, err: context canceled"
php_1        | [13-Nov-2017 22:45:50] WARNING: [pool www] child 50 said into stderr: "#13 /var/www/html/web/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)"
mailhog_1    | [APIv1] KEEPALIVE /api/v1/events
mariadb_1    | 2017-11-08  0:58:23 140526715271912 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
redis_1      |                 _._
nginx_1      | 172.18.0.5 - - [13/Nov/2017:21:39:07 +0000] "GET /core/assets/vendor/backbone/backbone-min.map HTTP/1.1" 200 33550 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
traefik_1    | time="2017-11-12T20:06:03Z" level=warning msg="Error forwarding to http://:80, err: context canceled"
php_1        | [13-Nov-2017 22:45:50] WARNING: [pool www] child 50 said into stderr: "#14 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array)"
mailhog_1    | [APIv1] KEEPALIVE /api/v1/events
mariadb_1    | 2017-11-08  0:58:25 140526715271912 [Note] InnoDB: Shutdown completed; log sequence number 2293380982

```

**Comment by rafatwork** [comment]
Experiencing this issue as well.

Doing
`docker-compose -p myproject exec php bash`
and after that
`ls -la`
...the folder with my codebase is showing empty.

Doing the following solved my issue:
`docker-compose -p myproject stop php nginx`
`docker-compose -p myproject rm php nginx`
`docker-compose -p myproject up -d`

**Comment by Max-Zviagintsev** [comment]
Thanks, it works for me!
