### ISSUE TITLE
 gyp verb `which` failed Error: not found: python2

### ISSUE THREAD

**Issue by holyorb2** [wodby/docker4drupal#321]
package.json

```
"devDependencies": {
    "gulp": "^3.9.1",
    "gulp-sass": "~2.3.1"
  }
```
Result

```
warning gulp-notify > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-sass > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-strip-css-comments > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-watch > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info If you think this is a bug, please open a bug report with the information provided in "/var/www/html/web/themes/custom/drupaltheme/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "/var/www/html/web/themes/custom/drupaltheme/node_modules/node-sass: Command failed.

Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /var/www/html/web/themes/custom/drupaltheme/node_modules/node-sass
Output:
Building: /usr/local/bin/node /var/www/html/web/themes/custom/drupaltheme/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/var/www/html/web/themes/custom/drupaltheme/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@9.11.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/html/web/themes/custom/drupaltheme/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/html/web/themes/custom/drupaltheme/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/html/web/themes/custom/drupaltheme/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/html/web/themes/custom/drupaltheme/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed   stack: 'Error: not found: python2\
    at getNotFoundError (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:13:12)\
    at F (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:68:19)\
    at E (/var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:80:29)\
    at /var/www/html/web/themes/custom/drupaltheme/node_modules/which/which.js:89:16\
    at /var/www/html/web/themes/custom/drupaltheme/node_modules/isexe/index.js:42:5\
    at /var/www/html/web/themes/custom/drupaltheme/node_modules/isexe/mode.js:8:5\
    at FSReqWrap.oncomplete (fs.js:170:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable \"python\" in the PATH
gyp verb `which` failed Error: not found: python
```

**Comment by csandanov** [comment]
`node-sass` package (the dependency of `gulp-sass`) supports alpine linux since 4.1.0 (https://github.com/sass/node-sass/issues/1589), installing a newer version of `gulp-sass` will fix that

**Comment by holyorb2** [comment]
"gulp-sass": "^3.1.0" - installed ok

Thanx

**Comment by petertogara** [comment]
erghjhckk

**Comment by petertogara** [comment]
Simply format your machine and start again

**Comment by StJohn3D** [comment]
Upgrading `"node-sass": "4.11.0"` -> `"node-sass": "4.12.0"` worked for me
