### ISSUE TITLE
Vanilla Drupal installation throws "Additional uncaught exception thrown while handling exception."

### ISSUE THREAD

**Issue by pasankg** [wodby/docker4drupal#452]
### Codebase
Built-in vanilla Drupal

### Issue
Once I visit http://drupal.docker.localhost:8000 it redirects to http://drupal.docker.localhost:8000/core/install.php and throws
```
Additional uncaught exception thrown while handling exception.
Original
Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' constraint (9.0.2) requires the 'core' key not be set in core/modules/block_place/block_place.info.yml in Drupal\Core\Extension\InfoParserDynamic->parse() (line 88 of /var/www/html/web/core/lib/Drupal/Core/Extension/InfoParserDynamic.php).

Drupal\Core\Extension\InfoParserDynamic->parse('core/modules/block_place/block_place.info.yml') (Line: 22)
Drupal\Core\Extension\InfoParser->parse('core/modules/block_place/block_place.info.yml') (Line: 88)
drupal_required_modules() (Line: 1120)
install_profile_info('demo_umami') (Line: 1294)
_install_select_profile(Array) (Line: 459)
install_begin_request(Object, Array) (Line: 115)
install_drupal(Object) (Line: 44)
Additional
Error: Call to undefined function Drupal\Core\Render\system_page_attachments() in Drupal\Core\Render\BareHtmlPageRenderer->renderBarePage() (line 65 of /var/www/html/web/core/lib/Drupal/Core/Render/BareHtmlPageRenderer.php).

Drupal\Core\Render\BareHtmlPageRenderer->renderBarePage(Array, 'Error', 'install_page', Array) (Line: 76)
Drupal\Core\ProxyClass\Render\BareHtmlPageRenderer->renderBarePage(Array, 'Error', 'install_page', Array) (Line: 1051)
install_display_output(Array, Array, Array) (Line: 267)
_drupal_log_error(Array, 1) (Line: 319)
_drupal_exception_handler(Object)
```
  
### Host OS 
macOS Catalina 10.15.6

### Docker info output
```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 10
  Paused: 0
  Stopped: 13
 Images: 36
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: FDLH:IDTB:6XIE:CK3D:GZM3:PCGJ:MJBE:FQXB:P2AV:6WKR:WXUC:VZ4D
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 123
  Goroutines: 119
  System Time: 2020-08-06T03:29:38.0049161Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Docker compose file
Make sure you remove all commented services.
```yml
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
    - ./:/var/www/html:cached

  crond:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - ./:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
    - ./:/var/www/html:cached
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '8000:80'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

### .env file
```
### Documentation available at https://wodby.com/docs/stacks/drupal/local
### Changelog can be found at https://github.com/wodby/docker4drupal/releases
### Images tags format explained at https://github.com/wodby/docker4drupal#images-tags

### PROJECT SETTINGS

PROJECT_NAME=my_drupal9_project
PROJECT_BASE_URL=drupal.docker.localhost

DB_NAME=drupal
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.4-3.8.5
### --- VANILLA DRUPAL ----

DRUPAL_TAG=9-4.20.4

### --- PHP ----

# Linux (uid 1000 gid 1000)

PHP_TAG=7.4-dev-4.17.1

# macOS (uid 501 gid 20)

#PHP_TAG=7.4-dev-macos-4.17.1
#PHP_TAG=7.3-dev-macos-4.17.1
#PHP_TAG=7.2-dev-macos-4.17.1

### --- NGINX ----

NGINX_TAG=1.19-5.10.2
#NGINX_TAG=1.18-5.10.2

NGINX_VHOST_PRESET=drupal9

### --- SOLR ---

SOLR_CONFIG_SET="search_api_solr_4.0"

SOLR_TAG=8-4.6.1

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=7-5.6.1

### --- KIBANA ---

KIBANA_TAG=7-5.6.1

### --- REDIS ---

REDIS_TAG=6-3.4.2

### --- NODE ---

NODE_TAG=14-dev-0.40.0

### --- VARNISH ---

VARNISH_TAG=6.0-4.4.8

### --- POSTGRESQL ----

POSTGRES_TAG=12-1.10.0

### OTHERS

ADMINER_TAG=4-3.10.1
APACHE_TAG=2.4-4.3.0
ATHENAPDF_TAG=2.10.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.6.0
OPENSMTPD_TAG=6.0-1.7.0
RSYSLOG_TAG=latest
SELENIUM_CHROME_TAG=3.141
WEBGRIND_TAG=1-1.16.1
XHPROF_TAG=2.3.1

```

### Logs output
```
Attaching to my_drupal9_project_nginx, my_drupal9_project_crond, my_drupal9_project_php, my_drupal9_project_portainer, my_drupal9_project_mailhog, my_drupal9_project_mariadb, my_drupal9_project_traefik
my_drupal9_project_crond | crond: crond (busybox 1.31.1) started, log level 0
my_drupal9_project_crond | crond: user:www-data entry:0 * * * * drush -r /var/www/html/web cron
my_drupal9_project_crond | 100000000000000000000000000000000000000000000000000000000000
my_drupal9_project_crond | 111111111111111111111111
my_drupal9_project_crond | 11111111111111111111111111111111
my_drupal9_project_crond | 111111111111
my_drupal9_project_crond | 1111111
my_drupal9_project_crond | crond: user:www-data entry:0 * * * * drush -r /var/www/html/web cron
my_drupal9_project_crond | 100000000000000000000000000000000000000000000000000000000000
my_drupal9_project_crond | 111111111111111111111111
my_drupal9_project_crond | 11111111111111111111111111111111
my_drupal9_project_crond | 111111111111
my_drupal9_project_crond | 1111111
my_drupal9_project_crond | crond: wakeup dt=26
my_drupal9_project_crond | crond: file www-data:
my_drupal9_project_crond | crond:  line drush -r /var/www/html/web cron
my_drupal9_project_crond | crond: wakeup dt=60
my_drupal9_project_crond | crond: file www-data:
my_drupal9_project_crond | crond:  line drush -r /var/www/html/web cron
my_drupal9_project_crond | crond: wakeup dt=60
my_drupal9_project_crond | crond: file www-data:
my_drupal9_project_crond | crond:  line drush -r /var/www/html/web cron
my_drupal9_project_crond | crond: wakeup dt=60
my_drupal9_project_crond | crond: file www-data:
my_drupal9_project_crond | crond:  line drush -r /var/www/html/web cron
my_drupal9_project_crond | crond: wakeup dt=60
my_drupal9_project_crond | crond: file www-data:
my_drupal9_project_crond | crond:  line drush -r /var/www/html/web cron
my_drupal9_project_crond | crond: wakeup dt=60
my_drupal9_project_crond | crond: file www-data:
my_drupal9_project_crond | crond:  line drush -r /var/www/html/web cron
my_drupal9_project_mariadb | Initializing database
my_drupal9_project_mariadb |
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
my_drupal9_project_mariadb | To do so, start the server, then issue the following commands:
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | '/usr/bin/mysqladmin' -u root password 'new-password'
my_drupal9_project_mariadb | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | Alternatively you can run:
my_drupal9_project_mariadb | '/usr/bin/mysql_secure_installation'
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | which will also give you the option of removing the test
my_drupal9_project_mariadb | databases and anonymous user created by default.  This is
my_drupal9_project_mariadb | strongly recommended for production servers.
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
my_drupal9_project_mariadb | MySQL manual for more instructions.
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | Please report any problems at http://mariadb.org/jira
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | The latest information about MariaDB is available at http://mariadb.org/.
my_drupal9_project_mariadb | You can find additional information about the MySQL part at:
my_drupal9_project_mariadb | http://dev.mysql.com
my_drupal9_project_mariadb | Consider joining MariaDB's strong and vibrant community:
my_drupal9_project_mariadb | https://mariadb.org/get-involved/
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | Database initialized
my_drupal9_project_mariadb | MySQL init process in progress...
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] mysqld (mysqld 10.4.13-MariaDB) starting as process 103 ...
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Using Linux native AIO
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Uses event mutexes
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Number of pools: 1
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Using SSE2 crc32 instructions
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Completed initialization of buffer pool
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Creating shared tablespace for temporary tables
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Waiting for purge to start
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: 10.4.13 started; log sequence number 60979; transaction id 21
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] Plugin 'FEEDBACK' is disabled.
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] InnoDB: Buffer pool(s) load completed at 200806  3:27:36
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Warning] 'user' entry 'root@2f812a90c5a7' ignored in --skip-name-resolve mode.
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Warning] 'user' entry '@2f812a90c5a7' ignored in --skip-name-resolve mode.
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Warning] 'proxies_priv' entry '@% root@2f812a90c5a7' ignored in --skip-name-resolve mode.
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] Reading of all Master_info entries succeeded
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] Added new Master_info '' to hash table
my_drupal9_project_mariadb | 2020-08-06  3:27:36 0 [Note] mysqld: ready for connections.
my_drupal9_project_mariadb | Version: '10.4.13-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
my_drupal9_project_mariadb | 2020-08-06  3:27:49 10 [Warning] 'proxies_priv' entry '@% root@2f812a90c5a7' ignored in --skip-name-resolve mode.
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | 2020-08-06  3:27:49 0 [Note] mysqld (initiated by: unknown): Normal shutdown
my_drupal9_project_mariadb | 2020-08-06  3:27:49 0 [Note] Event Scheduler: Purging the queue. 0 events
my_drupal9_project_mariadb | 2020-08-06  3:27:49 0 [Note] InnoDB: FTS optimize thread exiting.
my_drupal9_project_mariadb | 2020-08-06  3:27:49 0 [Note] InnoDB: Starting shutdown...
my_drupal9_project_mariadb | 2020-08-06  3:27:49 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
my_drupal9_project_mariadb | 2020-08-06  3:27:49 0 [Note] InnoDB: Buffer pool(s) dump completed at 200806  3:27:49
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Shutdown completed; log sequence number 60988; transaction id 24
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] mysqld: Shutdown complete
my_drupal9_project_mariadb |
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | MySQL init process done. Ready for start up.
my_drupal9_project_mariadb |
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] mysqld (mysqld 10.4.13-MariaDB) starting as process 1 ...
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Using Linux native AIO
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Uses event mutexes
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Number of pools: 1
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Using SSE2 crc32 instructions
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Completed initialization of buffer pool
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Creating shared tablespace for temporary tables
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Waiting for purge to start
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: 10.4.13 started; log sequence number 60988; transaction id 21
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] Plugin 'FEEDBACK' is disabled.
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] Server socket created on IP: '0.0.0.0'.
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Warning] 'proxies_priv' entry '@% root@2f812a90c5a7' ignored in --skip-name-resolve mode.
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] InnoDB: Buffer pool(s) load completed at 200806  3:27:50
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] Reading of all Master_info entries succeeded
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] Added new Master_info '' to hash table
my_drupal9_project_mariadb | 2020-08-06  3:27:50 0 [Note] mysqld: ready for connections.
my_drupal9_project_mailhog | 2020/08/06 03:27:31 Using in-memory storage
my_drupal9_project_mailhog | 2020/08/06 03:27:31 [SMTP] Binding to address: 0.0.0.0:1025
my_drupal9_project_mailhog | 2020/08/06 03:27:31 Serving under http://0.0.0.0:8025/
my_drupal9_project_mailhog | [HTTP] Binding to address: 0.0.0.0:8025
my_drupal9_project_mailhog | Creating API v1 with WebPath:
my_drupal9_project_mailhog | Creating API v2 with WebPath:
my_drupal9_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal9_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal9_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal9_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal9_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal9_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal9_project_mariadb | Version: '10.4.13-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: using the "epoll" event method
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: nginx/1.19.1
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0)
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: OS: Linux 4.19.76-linuxkit
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: start worker processes
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: start worker process 37
my_drupal9_project_nginx | 2020/08/06 03:27:32 [notice] 1#1: start worker process 38
my_drupal9_project_nginx | 172.29.0.2 - - [06/Aug/2020:03:28:28 +0000] "GET / HTTP/1.1" 302 326 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
my_drupal9_project_nginx | 2020/08/06 03:28:29 [error] 37#37: *1 FastCGI sent in stderr: "PHP message: Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' constraint (9.0.2) requires the 'core' key not be set in core/modules/block_place/block_place.info.yml in /var/www/html/web/core/lib/Drupal/Core/Extension/InfoParserDynamic.php on line 88 #0 /var/www/html/web/core/lib/Drupal/Core/Extension/InfoParser.php(22): Drupal\Core\Extension\InfoParserDynamic->parse('core/modules/bl...')
my_drupal9_project_nginx | #1 /var/www/html/web/core/includes/module.inc(88): Drupal\Core\Extension\InfoParser->parse('core/modules/bl...')
my_drupal9_project_nginx | #2 /var/www/html/web/core/includes/install.inc(1120): drupal_required_modules()
my_drupal9_project_nginx | #3 /var/www/html/web/core/includes/install.core.inc(1294): install_profile_info('demo_umami')
my_drupal9_project_nginx | #4 /var/www/html/web/core/includes/install.core.inc(459): _install_select_profile(Array)
my_drupal9_project_nginx | #5 /var/www/html/web/core/includes/install.core.inc(115): install_begin_request(Object(Composer\Autoload\ClassLoader), Array)
my_drupal9_project_nginx | #6 /var/www/html/web/core/install.php(44): install_drupal(Object(Composer\Autoload\ClassLoader))
my_drupal9_project_nginx | #7 {main}" while reading response header from upstream, client: 172.29.0.2, server: default, request: "GET /core/install.php HTTP/1.1", upstream: "fastcgi://172.29.0.5:9000", host: "drupal.docker.localhost:8000"
my_drupal9_project_nginx | 172.29.0.2 - - [06/Aug/2020:03:28:29 +0000] "GET /core/install.php HTTP/1.1" 200 715 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
my_drupal9_project_php | [06-Aug-2020 03:27:34] NOTICE: fpm is running, pid 1
my_drupal9_project_php | [06-Aug-2020 03:27:34] NOTICE: ready to handle connections
my_drupal9_project_php | 172.29.0.8 -  06/Aug/2020:03:28:28 +0000 "GET /index.php" 302
my_drupal9_project_php | NOTICE: PHP message: Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' constraint (9.0.2) requires the 'core' key not be set in core/modules/block_place/block_place.info.yml in /var/www/html/web/core/lib/Drupal/Core/Extension/InfoParserDynamic.php on line 88 #0 /var/www/html/web/core/lib/Drupal/Core/Extension/InfoParser.php(22): Drupal\Core\Extension\InfoParserDynamic->parse('core/modules/bl...')
my_drupal9_project_php | #1 /var/www/html/web/core/includes/module.inc(88): Drupal\Core\Extension\InfoParser->parse('core/modules/bl...')
my_drupal9_project_php | #2 /var/www/html/web/core/includes/install.inc(1120): drupal_required_modules()
my_drupal9_project_php | #3 /var/www/html/web/core/includes/install.core.inc(1294): install_profile_info('demo_umami')
my_drupal9_project_php | #4 /var/www/html/web/core/includes/install.core.inc(459): _install_select_profile(Array)
my_drupal9_project_php | #5 /var/www/html/web/core/includes/install.core.inc(115): install_begin_request(Object(Composer\Autoload\ClassLoader), Array)
my_drupal9_project_php | #6 /var/www/html/web/core/install.php(44): install_drupal(Object(Composer\Autoload\ClassLoader))
my_drupal9_project_php | #7 {main}
my_drupal9_project_php | 172.29.0.8 -  06/Aug/2020:03:28:28 +0000 "GET /core/install.php" 200
my_drupal9_project_portainer | 2020/08/06 03:27:31 Warning: the --no-auth flag is deprecated and will likely be removed in a future version of Portainer.
my_drupal9_project_portainer | 2020/08/06 03:27:31 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.
my_drupal9_project_portainer | 2020/08/06 03:27:33 server: Reverse tunnelling enabled
my_drupal9_project_portainer | 2020/08/06 03:27:33 server: Fingerprint a7:82:1e:80:f8:43:dc:54:6c:a2:f8:33:f7:00:67:f4
my_drupal9_project_portainer | 2020/08/06 03:27:33 server: Listening on 0.0.0.0:8000...
my_drupal9_project_portainer | 2020/08/06 03:27:33 Starting Portainer 1.24.1 on :9000
my_drupal9_project_portainer | 2020/08/06 03:27:33 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]
my_drupal9_project_traefik | time="2020-08-06T03:27:31Z" level=info msg="Configuration loaded from flags."
```

**Comment by jasonglisson** [comment]
Also getting the exact same issue.

**Comment by sschuchlenz** [comment]
same here, did you find a solution?

**Comment by pasankg** [comment]
I was not able to fix it
