### ISSUE TITLE
XHProf/Webgrind fails to start on Mac with M1 cpu

### ISSUE THREAD

**Issue by bozeak** [wodby/docker4drupal#511]
***OS type***
macOS

***Drupal version***
7 / 8

***Codebase***
Built-in vanilla Drupal or mounted codebase

**Describe the bug**
XHProf/Webgrind fails to start on MacOS with M1 cpu. It's just restarting permanently.
Any plans to add support for linux/arm64 for XHProf and Webgrind images?

**Logs output**
```
wodby/xhprof:latest
EXITED (2)



runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x6249a0, 0x9)

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90

runtime.newosproc(0xc82002e000, 0xc82003dfc0)

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:149 +0x18c

runtime.newm(0x676240, 0x0)

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1513 +0x135

runtime.main.func1()

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:125 +0x2c

runtime.systemstack(0x732c00)

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:291 +0x79

runtime.mstart()

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1048


goroutine 1 [running]:

runtime.systemstack_switch()

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc820028770 sp=0xc820028768

runtime.main()

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:126 +0x62 fp=0xc8200287c0 sp=0xc820028770

runtime.goexit()

/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200287c8 sp=0xc8200287c0
```

**Comment by csandanov** [comment]
Pushed new tags for xhprof and webgrind with arm64 support
